use_frameworks!

platform :ios, '10.0'

target 'SomeSupportnn_Example' do
  pod 'SomeSupportnn', :path => '../'

  target 'SomeSupportnn_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
